#!/usr/bin/env node

/**
 * AAF Design CLI — interactive design questionnaire.
 *
 * Walks through pillar questions, runs the deterministic trade-off engine,
 * and outputs an Agent Control Contract (ACC) in YAML + a trade-off report.
 *
 * Usage:
 *   node cli.js                    # interactive mode
 *   node cli.js --output acc.yaml  # save ACC to file
 *   node cli.js --json answers.json  # non-interactive: load answers from JSON
 */
import readline from "readline";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { matchByDesignAnswers } from "../engine/matcher.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.join(__dirname, "..", "data");

function loadPillars() {
  return JSON.parse(fs.readFileSync(path.join(DATA_DIR, "pillars.json"), "utf8"));
}

const AUTONOMY_LEVELS = ["assistive", "delegated", "bounded-autonomous", "supervisory"];

const args = process.argv.slice(2);
const outputIdx = args.indexOf("--output");
const outputPath = outputIdx >= 0 ? args[outputIdx + 1] : null;
const jsonIdx = args.indexOf("--json");
const jsonPath = jsonIdx >= 0 ? args[jsonIdx + 1] : null;

function createRL() {
  return readline.createInterface({ input: process.stdin, output: process.stderr });
}

function ask(rl, question) {
  return new Promise((resolve) => rl.question(question, resolve));
}

async function selectAutonomy(rl) {
  console.error("\nAutonomy levels:");
  AUTONOMY_LEVELS.forEach((l, i) => console.error(`  ${i + 1}. ${l}`));
  const raw = await ask(rl, "\nSelect autonomy level [1-4]: ");
  const idx = parseInt(raw, 10) - 1;
  if (idx < 0 || idx >= AUTONOMY_LEVELS.length) {
    console.error("Invalid selection, defaulting to 'delegated'.");
    return "delegated";
  }
  return AUTONOMY_LEVELS[idx];
}

async function askIntent(rl) {
  const intent = await ask(rl, "\nWhat does this agent do? (one line): ");
  return intent.trim() || "No intent specified";
}

async function walkQuestions(rl, pillars) {
  const answers = {};
  for (const pillar of pillars) {
    console.error(`\n--- ${pillar.name} ---`);
    answers[pillar.id] = {};
    for (let i = 0; i < pillar.questions.length; i++) {
      const qId = `${pillar.id}-q${i + 1}`;
      const raw = await ask(rl, `  ${pillar.questions[i]}\n  [yes/no/partial/skip] (default: skip): `);
      const answer = raw.trim().toLowerCase() || "skip";
      if (answer !== "skip") {
        answers[pillar.id][qId] = answer;
      }
    }
  }
  return answers;
}

function buildACC(answers, autonomyLevel, intent, pillars, tradeoffResults) {
  const lines = [
    "# Agent Control Contract (ACC)",
    `# Generated by: aaf design CLI`,
    `# Date: ${new Date().toISOString().slice(0, 10)}`,
    "",
    `intent: "${intent}"`,
    `autonomy_level: ${autonomyLevel}`,
    "",
    "pillars:",
  ];

  for (const p of pillars) {
    lines.push(`  ${p.id}:`);
    const pillarAnswers = answers[p.id] || {};
    for (let i = 0; i < p.questions.length; i++) {
      const qId = `${p.id}-q${i + 1}`;
      const answer = pillarAnswers[qId] || "not_assessed";
      lines.push(`    - question: "${p.questions[i]}"`);
      lines.push(`      answer: ${answer}`);
    }
  }

  if (tradeoffResults.length > 0) {
    lines.push("");
    lines.push("active_tradeoffs:");
    for (const t of tradeoffResults) {
      lines.push(`  - id: ${t.id}`);
      lines.push(`    pillars: [${t.pillars.join(", ")}]`);
      lines.push(`    tension: "${t.tension}"`);
      lines.push(`    recommendation: "${t.recommendation}"`);
      lines.push(`    match_strength: ${t.matchStrength.toFixed(2)}`);
    }
  }

  return lines.join("\n") + "\n";
}

function formatTradeoffReport(tradeoffResults) {
  if (tradeoffResults.length === 0) {
    return "\n--- Trade-off Analysis ---\nNo trade-off tensions detected for your design choices.\nThis may mean the trade-offs data model hasn't been populated yet.\n";
  }

  const lines = ["\n--- Trade-off Analysis ---", `${tradeoffResults.length} active tension(s):\n`];
  for (const t of tradeoffResults) {
    lines.push(`  [${t.pillars.join(" <-> ")}] (strength: ${(t.matchStrength * 100).toFixed(0)}%)`);
    lines.push(`    Tension: ${t.tension}`);
    lines.push(`    Recommendation: ${t.recommendation}`);
    if (t.source) lines.push(`    Source: ${t.source.doc} §${t.source.section}`);
    lines.push("");
  }
  return lines.join("\n");
}

async function runInteractive() {
  const rl = createRL();
  const pillars = loadPillars();

  console.error("=== AAF Design Questionnaire ===\n");
  console.error("This tool walks through the framework's pillar questions,");
  console.error("runs the deterministic trade-off engine, and outputs an ACC.\n");

  const autonomyLevel = await selectAutonomy(rl);
  const intent = await askIntent(rl);
  const answers = await walkQuestions(rl, pillars);

  rl.close();

  const tradeoffResults = matchByDesignAnswers(answers);
  const acc = buildACC(answers, autonomyLevel, intent, pillars, tradeoffResults);

  console.error(formatTradeoffReport(tradeoffResults));

  if (outputPath) {
    fs.writeFileSync(outputPath, acc, "utf8");
    console.error(`ACC written to: ${outputPath}`);
  } else {
    process.stdout.write(acc);
  }
}

function runFromJSON() {
  const pillars = loadPillars();
  const input = JSON.parse(fs.readFileSync(jsonPath, "utf8"));
  const { answers, autonomyLevel, intent } = input;

  if (!answers || !autonomyLevel) {
    console.error("JSON must contain: { answers, autonomyLevel, intent }");
    process.exit(1);
  }

  const tradeoffResults = matchByDesignAnswers(answers);
  const acc = buildACC(answers, autonomyLevel || "delegated", intent || "No intent", pillars, tradeoffResults);

  console.error(formatTradeoffReport(tradeoffResults));

  if (outputPath) {
    fs.writeFileSync(outputPath, acc, "utf8");
    console.error(`ACC written to: ${outputPath}`);
  } else {
    process.stdout.write(acc);
  }
}

if (jsonPath) {
  runFromJSON();
} else {
  runInteractive();
}
