/**
 * Pillar definitions: id, name, and review questions (from AAF application method).
 * Used by the CLI to structure the posture report.
 * Auto-generated by tools/scripts/sync-from-docs.js — do not edit by hand.
 */
export const PILLARS = [
  {
    id: "security",
    name: "Security Architecture",
    questions: [
      "Are all entry points authenticated and authorized?",
      "Are tool scopes least privilege?",
      "Are write actions gated and verified?",
      "Are untrusted inputs (including retrieved content) treated as hostile?",
    ],
  },
  {
    id: "reliability",
    name: "Reliability",
    questions: [
      "Is success defined as a verifiable end state?",
      "Are tool failures expected and handled?",
      "Are actions idempotent or checkpointed?",
      "Are retries safe?",
    ],
  },
  {
    id: "cost",
    name: "Cost Optimization",
    questions: [
      "Are budgets enforced at runtime?",
      "Is model routing explicit by phase and risk?",
      "Is context budgeted (no uncontrolled prompt accumulation)?",
      "Are caching and early stopping designed in?",
    ],
  },
  {
    id: "operational-excellence",
    name: "Operational Excellence",
    questions: [
      "Is the full loop observable (observe → decide → act → verify)?",
      "Is there an evaluation harness and regression suite?",
      "Is rollout staged with rollback?",
      "Are skills/tools versioned and reviewed?",
    ],
  },
  {
    id: "performance",
    name: "Performance Efficiency",
    questions: [
      "Is topology justified by task structure (single-agent by default; orchestration only where it helps)?",
      "Are tool round trips minimized?",
      "Is work partitioned into interactive vs batch?",
    ],
  },
  {
    id: "sustainability",
    name: "Sustainability",
    questions: [
      "Is usage measured and visible?",
      "Are efficiency levers used as defaults (minimal context, concise outputs, cached prefixes, bounded loops)?",
    ],
  },
  {
    id: "context-optimization",
    name: "Context Optimization (cross-cutting)",
    questions: [
      "Is context separated from memory (task-scoped vs durable)?",
      "Is context budgeted per task/step with explicit allocations?",
      "Is provenance tracked (trusted policy vs untrusted data)?",
      "Is retrieval/context construction minimal and explainable?",
    ],
  },
  {
    id: "autonomy-governance",
    name: "Autonomy & Outcome Governance (cross-cutting)",
    questions: [
      "Is autonomy level declared (assistive, delegated, bounded autonomous, supervisory)?",
      "Is there a Definition of Done with acceptance checks and evidence per task class?",
      "Are budgets (steps/tools/tokens/time/spend) enforced and visible?",
      "Are escalation triggers and degraded modes defined?",
    ],
  },
];
