/**
 * Formats security scan findings into markdown, JSON, or HTML reports.
 */

const SEVERITY_ORDER = { critical: 0, high: 1, medium: 2, low: 3 };

function sortFindings(findings) {
  return [...findings].sort((a, b) => (SEVERITY_ORDER[a.severity] ?? 9) - (SEVERITY_ORDER[b.severity] ?? 9));
}

function severityBadge(sev) {
  const badges = { critical: "🔴 CRITICAL", high: "🟠 HIGH", medium: "🟡 MEDIUM", low: "🔵 LOW" };
  return badges[sev] || sev.toUpperCase();
}

export function toMarkdown(findings, summary, targetPath) {
  const sorted = sortFindings(findings);
  const lines = [
    "# AAF Security Scan Report",
    "",
    `**Target:** \`${targetPath}\``,
    `**Date:** ${new Date().toISOString().split("T")[0]}`,
    "",
    "## Summary",
    "",
    `| Severity | Count |`,
    `|----------|-------|`,
    `| Critical | ${summary.critical} |`,
    `| High | ${summary.high} |`,
    `| Medium | ${summary.medium} |`,
    `| Low | ${summary.low} |`,
    `| **Total** | **${summary.total}** |`,
    "",
    "### By CIA Dimension",
    "",
    `| Dimension | Count |`,
    `|-----------|-------|`,
    `| Integrity | ${summary.by_cia.integrity} |`,
    `| Confidentiality | ${summary.by_cia.confidentiality} |`,
    `| Availability | ${summary.by_cia.availability} |`,
    "",
  ];

  if (sorted.length === 0) {
    lines.push("No security findings detected. Review manually for completeness.");
  } else {
    lines.push("## Findings", "");
    for (const f of sorted) {
      lines.push(
        `### ${severityBadge(f.severity)} — ${f.check}`,
        "",
        `- **CIA Dimension:** ${f.cia_dimension}`,
        `- **Location:** \`${f.location}\``,
        `- **Evidence:** ${f.evidence}`,
        `- **Recommendation:** ${f.recommendation}`,
        "",
      );
    }
  }

  lines.push(
    "---",
    "",
    "*Generated by `aaf security` — Agentic Architecture Framework*",
    "*Methodology: agenticaf.io/methodology*",
  );

  return lines.join("\n");
}

export function toJSON(findings, summary, targetPath) {
  return JSON.stringify({
    report: "aaf-security-scan",
    target: targetPath,
    date: new Date().toISOString().split("T")[0],
    summary,
    findings: sortFindings(findings),
  }, null, 2);
}

export function toHTML(findings, summary, targetPath) {
  const sorted = sortFindings(findings);
  const sevColor = { critical: "#dc2626", high: "#ea580c", medium: "#ca8a04", low: "#2563eb" };

  const findingsHTML = sorted.map((f) => `
    <div style="border:1px solid #e5e7eb;border-left:4px solid ${sevColor[f.severity] || "#6b7280"};border-radius:6px;padding:1rem;margin-bottom:0.75rem;">
      <strong style="color:${sevColor[f.severity] || "#6b7280"}">${f.severity.toUpperCase()}</strong> — ${f.check}
      <div style="font-size:0.9rem;margin-top:0.5rem;color:#374151;">
        <div><strong>CIA:</strong> ${f.cia_dimension} | <strong>Location:</strong> <code>${f.location}</code></div>
        <div><strong>Evidence:</strong> ${f.evidence}</div>
        <div style="margin-top:0.25rem;"><strong>Recommendation:</strong> ${f.recommendation}</div>
      </div>
    </div>`).join("\n");

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AAF Security Scan — ${targetPath}</title>
<style>body{font-family:system-ui,sans-serif;max-width:900px;margin:2rem auto;padding:0 1rem;color:#1a1a2e}
h1{font-size:1.5rem}h2{font-size:1.2rem;margin-top:2rem}
table{border-collapse:collapse;width:100%;margin:1rem 0}th,td{border:1px solid #e5e7eb;padding:0.5rem 0.75rem;text-align:left}
th{background:#f9fafb}code{background:#f3f4f6;padding:0.15em 0.3em;border-radius:3px;font-size:0.9em}</style>
</head><body>
<h1>AAF Security Scan Report</h1>
<p><strong>Target:</strong> <code>${targetPath}</code><br><strong>Date:</strong> ${new Date().toISOString().split("T")[0]}</p>
<h2>Summary</h2>
<table><tr><th>Severity</th><th>Count</th></tr>
<tr><td>Critical</td><td>${summary.critical}</td></tr>
<tr><td>High</td><td>${summary.high}</td></tr>
<tr><td>Medium</td><td>${summary.medium}</td></tr>
<tr><td>Low</td><td>${summary.low}</td></tr>
<tr><td><strong>Total</strong></td><td><strong>${summary.total}</strong></td></tr></table>
<h2>Findings</h2>
${sorted.length === 0 ? "<p>No security findings detected.</p>" : findingsHTML}
<hr><p style="font-size:0.85rem;color:#6b7280"><em>Generated by aaf security — Agentic Architecture Framework — agenticaf.io/methodology</em></p>
</body></html>`;
}
