/**
 * AAF MCP server — Vercel serverless route (Streamable HTTP).
 *
 * Core:      aaf_lookup, aaf_checklist, aaf_pillars_summary, aaf_get_skill,
 *            aaf_guide, aaf_list_skills, aaf_list_docs, aaf_get_doc
 * Workloads: aaf_list_workloads, aaf_workload_guidance
 * Design:    aaf_design_questions, aaf_tradeoff_analysis, aaf_tradeoff_catalog, aaf_generate_acc
 * Build:     aaf_scaffold_spec
 * Review:    aaf_posture_interpret, aaf_review_against_acc
 * Cross:     aaf_pillar_guidance
 * Security:  aaf_security_scan
 */
import { createMcpHandler, withMcpAuth } from "mcp-handler";
import { z } from "zod";
import {
  VALID_SKILL_IDS,
  VALID_WORKLOAD_IDS,
  analyseTradeoffs,
  getChecklist,
  getDocContent,
  getGuide,
  getPillarsSummary,
  getSkillContent,
  getWorkloadGuidance,
  listDocsMeta,
  listSkills,
  listWorkloadsCompact,
  loadAllTradeoffs,
  lookupInDocs,
  normalizePostureReport,
  rankWorkloads,
  safeReadJSON,
  serverInstructions,
  tradeoffCatalog,
  DATA_DIR,
} from "./lib/aaf-mcp-content";
import * as path from "path";

const VALID_PILLAR_IDS = [
  "security", "reliability", "cost", "operational-excellence",
  "performance", "sustainability", "context-optimization", "autonomy-governance",
] as const;

const AUTONOMY_LEVELS = ["assistive", "delegated", "bounded-autonomous", "supervisory"] as const;
const GUIDE_INTENTS = [
  "design", "workload", "tradeoffs", "review", "security", "lookup", "build", "general",
] as const;

function loadPillarsLocal(): any[] {
  return safeReadJSON(path.join(DATA_DIR, "pillars.json")) || [];
}

function getDesignQuestions(_autonomyLevel: string): any[] {
  const pillars = loadPillarsLocal();
  return pillars.map((p: any) => ({
    pillarId: p.id,
    pillarName: p.name,
    questions: p.questions.map((q: string, i: number) => ({
      questionId: `${p.id}-q${i + 1}`,
      text: q,
      expectedAnswer: "yes/no/partial",
      phase: "design",
    })),
  }));
}

function generateACC(
  answers: Record<string, Record<string, string>>,
  autonomyLevel: string,
  intent: string,
  workloadId?: string
): string {
  const pillars = loadPillarsLocal();
  const tradeoffResults = analyseTradeoffs(answers, workloadId);

  const yamlLines: string[] = [
    "# Agent Control Contract (ACC)",
    `# Generated by AAF MCP server`,
    `# Intent: ${intent}`,
    workloadId ? `# Workload: ${workloadId}` : null,
    "",
    `autonomy_level: ${autonomyLevel}`,
    "",
    "pillars:",
  ].filter((l) => l !== null) as string[];

  for (const p of pillars) {
    yamlLines.push(`  ${p.id}:`);
    const pillarAnswers = answers[p.id] || {};
    for (const q of p.questions) {
      const qId = `${p.id}-q${p.questions.indexOf(q) + 1}`;
      const answer = pillarAnswers[qId] || "not_answered";
      yamlLines.push(`    - question: "${q}"`);
      yamlLines.push(`      answer: "${answer}"`);
    }
  }

  if (tradeoffResults.length > 0) {
    yamlLines.push("");
    yamlLines.push("trade_offs:");
    for (const t of tradeoffResults) {
      yamlLines.push(`  - id: ${t.id}`);
      yamlLines.push(`    tension: "${t.tension}"`);
      yamlLines.push(`    recommendation: "${t.recommendation}"`);
    }
  }

  return yamlLines.join("\n");
}

function getScaffoldSpec(autonomyLevel: string): any {
  const baseFiles = [
    { path: "agent.py", purpose: "Main agent entry point with control loop" },
    { path: "policy.yaml", purpose: "Agent Control Contract (copied from design phase)" },
    { path: "tools/__init__.py", purpose: "Tool definitions with permission scopes" },
    { path: "gates.py", purpose: "Validation and epistemic gate implementations" },
    { path: "budgets.py", purpose: "Budget enforcement (steps, tokens, time, spend)" },
    { path: "observability.py", purpose: "Tracing hooks for observability trace" },
    { path: "tests/test_compliance.py", purpose: "Skeleton tests validating ACC compliance" },
    { path: "AGENTS.md", purpose: "Repository operating instructions" },
    { path: "AGENT_CONTROL_CONTRACT.md", purpose: "Human-readable ACC" },
    { path: "requirements.txt", purpose: "Python dependencies" },
  ];

  const levelDetails: Record<string, string> = {
    assistive: "Agent drafts, human approves everything. All tool calls gated.",
    delegated: "Agent proposes plans, human approves execution of write/delete actions.",
    "bounded-autonomous": "Agent executes within budgets, escalates on exceptions. Pre-approved action scopes.",
    supervisory: "Supervisor + worker pattern with nested sub-contracts.",
  };

  return {
    autonomyLevel,
    levelDescription: levelDetails[autonomyLevel] || levelDetails["delegated"],
    files: baseFiles,
    controlLoop: "Trigger → Interpret Context → Decide → Act → Observe Results → Verify → [Adapt / Stop]",
    observabilityTrace: "intent → plan → act → verify",
  };
}

function interpretPosture(reportInput: any): any {
  const report = normalizePostureReport(reportInput);
  const tradeoffs = loadAllTradeoffs();
  const scores: Record<string, number> = {};

  for (const [pillarId, results] of Object.entries(report)) {
    if (!Array.isArray(results)) continue;
    const found = results.filter((r: any) => r.status === "found").length;
    scores[pillarId] = results.length > 0 ? found / results.length : 0;
  }

  const tensions: any[] = [];
  for (const entry of tradeoffs) {
    if (!entry.pillars || entry.pillars.length < 2) continue;
    const [pA, pB] = entry.pillars;
    const sA = scores[pA];
    const sB = scores[pB];
    if (sA === undefined || sB === undefined) continue;
    const delta = Math.abs(sA - sB);
    if (delta >= 0.3) {
      tensions.push({
        id: entry.id,
        pillars: entry.pillars,
        workloadId: entry.workloadId || null,
        tension: entry.tension,
        recommendation: entry.recommendation,
        source: entry.source,
        highPillar: sA > sB ? pA : pB,
        lowPillar: sA > sB ? pB : pA,
        scoreDelta: delta,
      });
    }
  }

  return {
    scores,
    tensions: tensions.sort((a: any, b: any) => b.scoreDelta - a.scoreDelta),
    note: "Posture scores are heuristic. Manual review still required for production readiness.",
  };
}

function reviewAgainstACC(accYaml: string, reportInput: any): any {
  const report = normalizePostureReport(reportInput);
  const gaps: any[] = [];
  const pillars = loadPillarsLocal();

  for (const pillar of pillars) {
    const pillarResults = report[pillar.id];
    if (!Array.isArray(pillarResults)) continue;

    for (const result of pillarResults) {
      if (result.status === "not_found") {
        const accMentions = accYaml.includes(result.question);
        gaps.push({
          pillarId: pillar.id,
          question: result.question,
          severity: accMentions ? "high" : "medium",
          detail: accMentions
            ? "Specified in ACC but not detected in codebase"
            : "Not detected in codebase",
        });
      }
    }
  }

  return {
    totalGaps: gaps.length,
    gaps: gaps.sort((a: any, b: any) => (a.severity === "high" ? -1 : 1) - (b.severity === "high" ? -1 : 1)),
  };
}

function getPillarGuidance(pillarId: string): any {
  const pillars = loadPillarsLocal();
  const tradeoffs = loadAllTradeoffs();
  const pillar = pillars.find((p: any) => p.id === pillarId);
  if (!pillar) return null;

  const relevantTradeoffs = tradeoffs.filter((t: any) => (t.pillars || []).includes(pillarId));

  return {
    pillarId: pillar.id,
    pillarName: pillar.name,
    questions: pillar.questions,
    tradeoffs: relevantTradeoffs.map((t: any) => ({
      id: t.id,
      workloadId: t.workloadId || null,
      otherPillar: t.pillars.find((p: string) => p !== pillarId),
      tension: t.tension,
      recommendation: t.recommendation,
      source: t.source,
      confidence: t.confidence,
      autonomyNotes: t.autonomyNotes,
    })),
  };
}

function jsonText(data: unknown) {
  return { content: [{ type: "text" as const, text: JSON.stringify(data, null, 2) }] };
}

// ─── MCP server registration ────────────────────────────────────────────────

const baseHandler = createMcpHandler(
  (server) => {
    server.registerTool("aaf_guide", {
      title: "AAF Guide",
      description:
        "Call this FIRST when unsure which AAF tool to use. Returns an ordered tool plan for design, workload selection, trade-offs, review, security, lookup, or build. For intent=review, includes terminal commands to run the local aaf-posture CLI before interpret tools.",
      inputSchema: {
        intent: z.enum(GUIDE_INTENTS).optional().describe("What you are trying to do"),
        question: z.string().optional().describe("Optional free-text architecture question"),
      },
    }, async ({ intent, question }) => jsonText(getGuide(intent, question)));

    server.registerTool("aaf_list_skills", {
      title: "AAF List Skills",
      description: "List AAF skill ids and one-line purposes before calling aaf_get_skill.",
      inputSchema: {},
    }, async () => jsonText({ skills: listSkills() }));

    server.registerTool("aaf_list_docs", {
      title: "AAF List Docs",
      description: "List framework doc filenames and titles. Use aaf_get_doc to load content.",
      inputSchema: {},
    }, async () => jsonText({ docs: listDocsMeta() }));

    server.registerTool("aaf_get_doc", {
      title: "AAF Get Doc",
      description:
        "Load a framework doc by filename (e.g. 13.51-workload-knowledge-assistant.md). Optional section heading substring and maxChars/offset for chunking.",
      inputSchema: {
        docId: z.string().describe("Doc filename under docs/"),
        section: z.string().optional().describe("Optional heading substring to extract"),
        maxChars: z.number().int().positive().max(20000).optional(),
        offset: z.number().int().nonnegative().optional(),
      },
    }, async ({ docId, section, maxChars, offset }) => {
      const result = getDocContent(docId, { section, maxChars, offset });
      if ("error" in result) return { content: [{ type: "text", text: result.error }], isError: true };
      return jsonText(result);
    });

    server.registerTool("aaf_list_workloads", {
      title: "AAF List Workloads",
      description:
        "Start here when choosing an agentic system shape. Lists Common Agentic Workloads plus the minimum-complexity heuristic. Optional requirements text ranks nearest workloads.",
      inputSchema: {
        requirements: z.string().optional().describe("Free-text requirements to rank nearest workloads"),
      },
    }, async ({ requirements }) => {
      const catalog = listWorkloadsCompact();
      if (requirements?.trim()) {
        return jsonText({ ...catalog, ranked: rankWorkloads(requirements) });
      }
      return jsonText(catalog);
    });

    server.registerTool("aaf_workload_guidance", {
      title: "AAF Workload Guidance",
      description:
        "Return rubrics, review focus, dominant cross-pillar / Cost×Accuracy×Speed trades, failure modes, and when-not-this for a workload id.",
      inputSchema: {
        workloadId: z.enum(VALID_WORKLOAD_IDS),
        includeDoc: z.boolean().optional().describe("If true, include a large doc excerpt"),
      },
    }, async ({ workloadId, includeDoc }) => {
      const guidance = getWorkloadGuidance(workloadId, includeDoc === true);
      if (guidance.error) return { content: [{ type: "text", text: guidance.error }], isError: true };
      return jsonText(guidance);
    });

    server.registerTool("aaf_tradeoff_catalog", {
      title: "AAF Trade-off Catalog",
      description: "List trade-off ids with pillar pairs, optional workload tags, and one-line tensions.",
      inputSchema: {
        workloadId: z.enum(VALID_WORKLOAD_IDS).optional(),
      },
    }, async ({ workloadId }) => jsonText({ tradeoffs: tradeoffCatalog(workloadId) }));

    server.registerTool("aaf_lookup", {
      title: "AAF Lookup",
      description:
        "Search framework docs for a term or topic. Returns ranked matches with larger excerpts. Prefer aaf_get_doc for full sections; use aaf_list_workloads for system-shape choice.",
      inputSchema: { query: z.string().min(1) },
    }, async ({ query }) => {
      const { matches, hint } = lookupInDocs(query);
      if (!matches.length) return { content: [{ type: "text", text: hint }] };
      return jsonText({ matches, hint });
    });

    server.registerTool("aaf_checklist", {
      title: "AAF Checklist",
      description:
        "Return the AAF architecture checklist. kind=review (default) for pre-production readiness; kind=design for Mode 1 design-time checklist.",
      inputSchema: { kind: z.enum(["review", "design"]).optional() },
    }, async ({ kind }) => ({
      content: [{ type: "text", text: getChecklist(kind ?? "review") }],
    }));

    server.registerTool("aaf_pillars_summary", {
      title: "AAF Pillars Summary",
      description: "Short summary of the six AAF pillars and cross-cutting foundations. Use when orienting before deeper pillar or workload work.",
      inputSchema: {},
    }, async () => ({
      content: [{ type: "text", text: getPillarsSummary() }],
    }));

    server.registerTool("aaf_get_skill", {
      title: "AAF Get Skill",
      description:
        "Return full content of an AAF skill by id. Call aaf_list_skills first if unsure. Skills: aaf-architecture-review, aaf-security, aaf-epistemic-gates, aaf-cost-context, aaf-cross-cutting, aaf-acc-implementation, aaf-orchestration-occ.",
      inputSchema: { skillId: z.enum(VALID_SKILL_IDS) },
    }, async ({ skillId }) => {
      const text = getSkillContent(skillId);
      if (!text) return { content: [{ type: "text", text: `Skill not found: ${skillId}` }], isError: true };
      return { content: [{ type: "text", text }] };
    });

    server.registerTool("aaf_design_questions", {
      title: "AAF Design Questions",
      description:
        "Return the full design questionnaire for an autonomy level. Prefer selecting a workload (aaf_list_workloads) first when designing a new system.",
      inputSchema: {
        autonomyLevel: z.enum(AUTONOMY_LEVELS).describe("The autonomy level of the agent being designed"),
      },
    }, async ({ autonomyLevel }) => {
      const questions = getDesignQuestions(autonomyLevel);
      return jsonText({ autonomyLevel, pillars: questions });
    });

    server.registerTool("aaf_tradeoff_analysis", {
      title: "AAF Trade-off Analysis",
      description:
        "Deterministic trade-off engine from design choices. Optional workloadId includes workload-scoped dominant trades. Same input → same output.",
      inputSchema: {
        choices: z.record(z.record(z.string())).describe("Design answers keyed by pillar ID then question ID"),
        workloadId: z.enum(VALID_WORKLOAD_IDS).optional(),
      },
    }, async ({ choices, workloadId }) => {
      const results = analyseTradeoffs(choices, workloadId);
      if (results.length === 0) {
        return {
          content: [{
            type: "text",
            text: "No trade-off tensions matched. Try aaf_tradeoff_catalog, pass workloadId, or call aaf_workload_guidance for dominant trades.",
          }],
        };
      }
      return jsonText({ activeTradeoffs: results.length, workloadId: workloadId || null, tradeoffs: results });
    });

    server.registerTool("aaf_generate_acc", {
      title: "AAF Generate ACC",
      description:
        "Generate an Agent Control Contract (ACC) YAML from design answers. Optional workloadId tags the ACC and includes workload trades.",
      inputSchema: {
        answers: z.record(z.record(z.string())).describe("Design answers keyed by pillar ID then question ID"),
        autonomyLevel: z.enum(AUTONOMY_LEVELS),
        intent: z.string().describe("One-line description of what the agent does"),
        workloadId: z.enum(VALID_WORKLOAD_IDS).optional(),
      },
    }, async ({ answers, autonomyLevel, intent, workloadId }) => ({
      content: [{ type: "text", text: generateACC(answers, autonomyLevel, intent, workloadId) }],
    }));

    server.registerTool("aaf_scaffold_spec", {
      title: "AAF Scaffold Spec",
      description:
        "Return the file manifest aaf build would generate for an autonomy level (paths, purposes, control loop). Use after ACC generation.",
      inputSchema: {
        autonomyLevel: z.enum(AUTONOMY_LEVELS),
      },
    }, async ({ autonomyLevel }) => jsonText(getScaffoldSpec(autonomyLevel)));

    server.registerTool("aaf_posture_interpret", {
      title: "AAF Posture Interpret",
      description:
        "Interpret a posture report into per-pillar scores and trade-off tensions. FIRST run the local CLI in the project terminal: `node tools/aaf-posture/cli.js . --format json --output ./aaf-posture.json` (install once under tools/aaf-posture). Then pass the JSON file contents as report. Accepts raw CLI output ({ path, scannedFiles, pillars }) or a flat pillarId→items map. Hosted MCP cannot scan the user's disk.",
      inputSchema: {
        report: z.any().describe("CLI JSON from aaf-posture --format json, or flat map of pillarId → [{question,status,evidence}]"),
      },
    }, async ({ report }) => jsonText(interpretPosture(report)));

    server.registerTool("aaf_review_against_acc", {
      title: "AAF Review Against ACC",
      description:
        "Gap analysis between an ACC YAML string and a posture report. Use after running the local posture CLI. report accepts the same shapes as aaf_posture_interpret (raw CLI JSON or flat map).",
      inputSchema: {
        accYaml: z.string().describe("The Agent Control Contract as a YAML string"),
        report: z.any().describe("CLI JSON from aaf-posture --format json, or flat pillar→items map"),
      },
    }, async ({ accYaml, report }) => jsonText(reviewAgainstACC(accYaml, report)));

    server.registerTool("aaf_pillar_guidance", {
      title: "AAF Pillar Guidance",
      description:
        "Targeted design considerations for one pillar: review questions plus related pillar and workload trade-offs.",
      inputSchema: {
        pillarId: z.enum(VALID_PILLAR_IDS),
      },
    }, async ({ pillarId }) => {
      const guidance = getPillarGuidance(pillarId);
      if (!guidance) return { content: [{ type: "text", text: `Pillar not found: ${pillarId}` }], isError: true };
      return jsonText(guidance);
    });

    server.registerTool("aaf_security_scan", {
      title: "AAF Security Scan",
      description:
        "CIA-aligned security checks on file path + snippet findings. Prefer loading aaf-security skill first for process context.",
      inputSchema: {
        findings: z.array(z.object({
          file: z.string().describe("Relative file path"),
          snippet: z.string().describe("Relevant code snippet or content from the file"),
        })).describe("Array of file paths and content snippets to analyse"),
        severity: z.enum(["critical", "high", "medium", "all"]).optional().describe("Minimum severity to include (default: all)"),
      },
    }, async ({ findings: inputFindings, severity }) => {
      const content = new Map<string, string>();
      const filePaths: string[] = [];
      for (const f of inputFindings) {
        content.set(f.file, f.snippet);
        filePaths.push(f.file);
      }

      const { runSecurityChecks } = await import("../tools/aaf-security/checks.js") as {
        runSecurityChecks: (s: { paths: string[]; content: Map<string, string> }) => { findings: any[]; summary: any };
      };
      const { findings: allFindings } = runSecurityChecks({ paths: filePaths, content });

      const sevOrder: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };
      const minSev = severity === "all" || !severity ? 999 : (sevOrder[severity] ?? 999);
      const filtered = allFindings.filter((f: any) => (sevOrder[f.severity] ?? 999) <= minSev);

      const summary = {
        total: filtered.length,
        critical: filtered.filter((f: any) => f.severity === "critical").length,
        high: filtered.filter((f: any) => f.severity === "high").length,
        medium: filtered.filter((f: any) => f.severity === "medium").length,
        low: filtered.filter((f: any) => f.severity === "low").length,
      };

      return jsonText({ summary, findings: filtered });
    });
  },
  {
    serverInfo: { name: "aaf-mcp", version: "2.0.0" },
    instructions: serverInstructions(),
  },
  { basePath: "/api", maxDuration: 30 }
);

// ─── Auth ───────────────────────────────────────────────────────────────────

import { authErrorResponse, gateMcpRequest } from "./lib/mcp-auth";

const verifyToken = async (
  _req: Request,
  bearerToken?: string
): Promise<{ token: string; scopes: string[]; clientId: string } | undefined> => {
  const apiKey = process.env.MCP_API_KEY;
  if (!apiKey) return undefined;
  if (!bearerToken || bearerToken !== apiKey) return undefined;
  return { token: bearerToken, scopes: ["read:aaf"], clientId: "api-key" };
};

const authHandler = withMcpAuth(baseHandler, verifyToken, {
  required: false,
  requiredScopes: ["read:aaf"],
  resourceMetadataPath: "/.well-known/oauth-protected-resource",
});

async function withMcpBillingGate(
  req: Request,
  handler: (req: Request) => Promise<Response> | Response
): Promise<Response> {
  const gate = await gateMcpRequest(req);
  if (!gate.ok) return authErrorResponse(gate);
  return handler(req);
}

export const GET = (req: Request) => withMcpBillingGate(req, authHandler);
export const POST = (req: Request) => withMcpBillingGate(req, authHandler);
export const DELETE = (req: Request) => withMcpBillingGate(req, authHandler);
